
import 'package:flutter/material.dart';
import '../shared/info/widgets/info.dart';

class Norms extends StatelessWidget{

  final String id;

  Norms({
    Key key,
    @required this.id,
  });

  @override
  Widget build(BuildContext context) {

    Map<String, List<String>> config = Map();

    config['norm_constitucion_republica'] = [
      'Constitución de la Republica',
      '\n•  Art. 14 Se reconoce el derecho de la población a vivir en un ambiente sano y ecológicamente equilibrado, que garantice la sostenibilidad y el buen vivir, sumak kawsay. \n\nSe declara de interés público la preservación del ambiente, la conservación de los ecosistemas, la biodiversidad y la integridad del patrimonio genético del país, la prevención del daño ambiental y la recuperación de los espacios naturales degradados.\n\n\n•  Art. 406 menciona que “el Estado regulará la conservación, manejo y uso sustentable, recuperación, y limitaciones de dominio de los ecosistemas frágiles y amenazados; entre otros, los páramos, humedales, bosques nublados, bosques tropicales secos y húmedos y manglares, ecosistemas marinos y marinos-costeros.”',];

    config['norm_codigo_organico'] = [
      'Código Orgánico del Ambiente',
      '\n•  Art. 99 del COA “Será de interés público la conservación, protección y restauración de los manglares”\n\n\n•  Art. 103 del COA se menciona que “el ecosistema manglar es un bien del Estado…” y “…solamente podrá ser aprovechado sosteniblemente mediante concesión otorgada o renovada por el Ministerio rector del ámbito pesquero.” “Las comunas, comunidades, pueblos y nacionalidades ancestrales podrán solicitar se les conceda la custodia y uso sostenible del manglar para su subsistencia, aprovechamiento y comercialización exclusiva de peces, moluscos y crustáceos, entre otras especies, que se desarrollen en este hábitat.”\n\nEn cuanto al aprovechamiento sostenible de los recursos marinos costeros en artículo 275 dice que el aprovechamiento sostenible de los recursos marinos y costeros deberá:\n\n1. Mantener la diversidad, calidad y disponibilidad de los recursos pesqueros a fin de garantizar los procesos ecológicos y satisfacer las necesidades de las generaciones presentes y futuras, en el contexto de la soberanía alimentaria y el desarrollo sostenible;\n\n2. Asegurar la conservación no sólo de las especies que son objeto de uso directo, sino también de aquellas dependientes o asociadas al mismo ecosistema; \n\n3. Evitar su sobreexplotación para asegurar que el esfuerzo pesquero sea proporcional a la capacidad de producción de estos recursos;\n\n4. Basarse en los datos científicos disponibles para la toma de decisiones, considerando los conocimientos tradicionales acerca de los recursos y su hábitat, así como los factores ambientales, económicos y sociales pertinentes;\n\n5. Garantizar la protección y restauración de los habitáis críticos para la pesca en los ecosistemas marinos, especialmente los manglares, los arrecifes, ecosistemas coralinos, zonas de cría y desove;\n\n6. Asegurar conjuntamente con la autoridad competente el ejercicio de los derechos de los pescadores artesanales a realizar, en las aguas de jurisdicción nacional, su actividad, y el acceso preferencial, cuando proceda, a los recursos pesqueros y zonas tradicionales de pesca; y,\n\n7. Promover la cooperación bilateral, regional y multilateral en la investigación y conservación, reconociendo la naturaleza transfronteriza de los ecosistemas acuáticos.”',];

    config['ley_pesca_desarrollo'] = [
      'Ley de Pesca y Desarrollo Pesquero',
      '\n•  Art. 43 de la LPDP “son obligaciones de las personas naturales o jurídicas que ejerzan cualquiera de las actividades en la actividad pesquera: capturar sólo las especies bioacuáticas cuya pesca esté permitida y sujetarse a la reglamentación sobre tamaño, períodos de veda”',];

    config['reglamento_coa'] = [
      'Reglamento del COA',
      '\n•  Art. 263 La Autoridad Ambiental Nacional delimitará las zonas de ecosistemas de manglar y elaborará un plan de ordenamiento que incluya la zonificación y la determinación de:\n\na) Las áreas susceptibles de uso sostenible del ecosistema de manglar por parte de usuarios tradicionales: las comunas, comunidades, pueblos y nacionalidades, mediante acuerdos de uso sostenible y custodia, otorgados por la Autoridad Ambiental Nacional; y,\n\nb) Las áreas disponibles para ser otorgadas bajo concesión pesquera en ecosistema de manglar, por parte de la Autoridad Nacional de Pesca.\n\nArt 264. La Autoridad Ambiental Nacional es competente para otorgar y regular los acuerdos de uso sostenible y custodia del ecosistema de manglar, cuyas especificaciones técnicas se establecerán en la respectiva norma secundaria, la que incluirá las regulaciones para el manejo, uso y conservación del ecosistema de manglar.\n\n\n•  Art. 265. Los acuerdos de uso sostenible y custodia del ecosistema de manglar constituyen un mecanismo para la conservación, otorgados por la Autoridad Ambiental Nacional. Estos acuerdos se pueden otorgar y conceder a los usuarios del manglar que realizan actividades tradicionales permitidas dentro del manglar, que gocen de personería jurídica y estén organizados en comunas, asociaciones, cooperativas u otra modalidad de organización de usuarios tradicionales legalmente reconocidas.\n\nDichos acuerdos tendrían una duración de diez (10) años pudiendo renovarse a solicitud expresa y previo cumplimiento de los requisitos establecidos en este Reglamento y la norma secundaria. El otorgamiento de los acuerdos de uso sostenible y custodia del ecosistema de manglar se basará en los siguientes principios: a) Garantizar la conservación del ecosistema manglar; b) Mantener la cobertura de la vegetación del ecosistema de manglar; c) Otorgar seguridad jurídica respecto de los derechos dec uso de usuarios tradicionales; d) Uso de recursos extractivos de manera sostenible, evitando la sobreexplotación y garantizando la capacidad de resiliencia del ecosistema de manglar; e) Manejo participativo e inclusivo de las áreas en custodia, identificando a todos los usuarios y promoviendo un ordenamiento y control participativo; y, f) Asegurar el mantenimiento de servicios ambientales del ecosistema de manglar.\n\n\n•  Art. 737. Son instrumentos para la gestión ambiental marino costera: f) Planes de Manejo para los Acuerdos de uso sostenible y custodia de ecosistemas marinos y costeros frágiles, tales como manglar, salitrales, comunidades coralinas, fondos rocosos y arenosos, playas, bajos de pesca, entre otros. ',];

    config['legislacion_mae'] = [
      'Legislación Ambiental Secundaria del Ministerio del Ambiente',
      '\n•  Art. 179 del TULSMA dice que “en el Patrimonio Nacional de Áreas Naturales, el Ministerio del Ambiente podrá otorgar concesiones y celebrar contratos de comodato, arrendamiento y cualquier otra figura legal adecuada para la prestación de servicios o la utilización sustentable de recursos de las áreas naturales del Estado, con base al respectivo plan de manejo y en función de la categoría de manejo del área protegida.”',];

    config['auscm'] = [
      'Acuerdos de Uso Sostenible y Custodia del Ecosistema Manglar',
      '\n•  Art. 1 del Acuerdo Miniterial 172 (enero 2000) se establece que “el uso sustentable de un área determinada de manglar se concederá a las comunidades y grupos usuarios de la misma, que gozando de personería jurídica y organizados en asociaciones o cooperativas, así lo soliciten ante el Subsecretario de Desarrollo Sostenible (hoy Subsecretaría de Gestión Marina y Costera) con sede en la ciudad de Guayaquil.\n\n\n•  Art. 2 del Acuerdo Ministerial 129 (agosto 2010) menciona que el uso sustentable de un área de manglar se refiere al aprovechamiento no destructivo de los recursos naturales de este ecosistema e incluye las siguientes actividades:\n\na) Pesca extractiva de peces e invertebrados;\n\nb) Cría, engorde o cultivo de peces, invertebrados, mamíferos, reptiles u otras especies de la fauna nativa mediante prácticas que no afecten la cobertura de manglar o la dinámica de los cuerpos hídricos;\n\nc) Manejo forestal controlado;\n\nd) Reforestación del manglar;\n\ne) Turismo ecológico y actividades de recreación no destructivas del manglar;\n\nf) Conservación y protección; y,\n\ng) Educación e investigación científica.\n\n\n•  Art. 9 del Acuerdo Ministerial 129 (agosto 2010) contempla en su numeral d) que los concesionarios deberán: “Informar semestralmente sobre el estado del uso sustentable y custodia del manglar y los avances en el cumplimiento del Plan de Manejo para Uso Sustentable y Custodia del Manglar.” Así mismo, el artículo 12 establece que el concesionario tiene la obligación de cumplir con los requisitos que se detallan a continuación:\n\na) Entregar a tiempo los informes y evaluaciones antes indicados;\n\nb) Cumplir el calendario de implementación del Plan de Manejo aprobado en el Acuerdo de Uso Sustentable y Custodia de Manglar; e,\n\nc) Informar oportunamente de los cambios en la organización beneficiaria (e.j., cambio de directiva, ingreso de nuevos socios, actualización de estatutos o reglamentos).\n\n\n•  Art. 10.- Se producirá la terminación del Acuerdo de Uso Sustentable y Custodia de Manglar en los siguientes casos:\n\na) Por vencimiento del plazo;\n\nb) Por mutuo acuerdo entre las partes; y,\n\nc) Por incumplimiento de cualquiera de las obligaciones contenidas en las leyes aplicables o en el plan de manejo aprobado por la autoridad ambiental.\n\n\n•  Art. 13. El acuerdo ministerial que otorga el uso sustentable y custodia del manglar será comunicado con fines informativos a la autoridad marítima, de pesca, de acuacultura, de turismo, y de policía.',];

    List<String> normInfo = config[id];
    return Info(title: normInfo[0], info: Text(normInfo[1]));

  }

}
